defaults:
  - _self_
  # - dataset@dataset: mnist_collage
  # - feature_extractor@model.feature_extractor: mnist
  # - classifier@model.classifier: linear
  # - optimizer@optimizer: adamw

settings:
  feature_dim: 768

name: experiment
output_dir: /mnt/bulk/gwoelflein/georg-transformers/output/${name}
seed: 0 # leave empty to use random seed
dataset:
  clini_tables: ["/mnt/bulk/gwoelflein/georg-transformers/metadata/MSKCC-BRCA-DX_Cohort_1_CLINI.xlsx"]
  slide_tables: ["/mnt/bulk/gwoelflein/georg-transformers/metadata/MSKCC-BRCA-DX_SLIDE.csv"]
  feature_dirs: ["/mnt/bulk/gwoelflein/georg-transformers/data/MSKCC-BRCA-DX_BATCH1/ctranspath"]
  filename_col: FILENAME
  patient_col: PATIENT
  targets:
    - column: HER2_3groups
      type: categorical
      classes: [HER2high, HER2low, HER2no]
      weights: # optional
  batch_size: 1
  instances_per_bag: 4096
  pad: False
  num_workers: 16
model:
  _target_: pubfork.model.MilTransformer
  d_features: 768
  targets: ${dataset.targets}
learning_rate: 1e-4
max_epochs: 50
patience: 10
accumulate_grad_samples: 16
grad_clip: .5
